import React, { useEffect, useState } from 'react';
import { accountsService } from '../api/client';
import { useAuth } from '../context/AuthContext';
import Modal from '../components/ui/Modal.jsx';

const roles = ['client', 'creator', 'moderator', 'admin', 'superadmin'];
const labels = { superadmin: 'Superadministrador', admin: 'Administrador', moderator: 'Moderador', creator: 'Creador', client: 'Cliente' };
const empty = { name: '', email: '', password: '', role: 'client' };

export default function AccountsPanel() {
  const { user: session, isSuperadmin } = useAuth();
  const [users, setUsers] = useState([]), [query, setQuery] = useState(''), [role, setRole] = useState('all');
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState(''), [retry, setRetry] = useState(0);
  const [creating, setCreating] = useState(false), [form, setForm] = useState(empty), [pending, setPending] = useState(false), [confirmDelete, setConfirmDelete] = useState(null);
  const [creditIds, setCreditIds] = useState([]), [creditAmount, setCreditAmount] = useState(100), [creditNote, setCreditNote] = useState('Recarga de prueba'), [creditModal, setCreditModal] = useState(false);
  const load = () => accountsService.list().then(data => setUsers(data.users));
  useEffect(() => { let active = true; setLoading(true); setError(''); accountsService.list().then(data => active && setUsers(data.users)).catch(err => active && setError(err.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [retry]);
  const shown = users.filter(account => (role === 'all' || role === account.role) && [account.name, account.email].some(value => String(value || '').toLowerCase().includes(query.toLowerCase())));
  async function createAccount(event) { event.preventDefault(); setPending(true); setError(''); try { await accountsService.create(form); await load(); setForm(empty); setCreating(false); setNotice('Cuenta creada correctamente.'); } catch (err) { setError(err.message); } finally { setPending(false); } }
  async function changeRole(account, nextRole) { setPending(true); setError(''); try { const result = await accountsService.setRole(account.id, nextRole); setUsers(current => current.map(item => item.id === account.id ? result.user : item)); setNotice(`Rol de ${account.name || account.email} actualizado.`); } catch (err) { setError(err.message); } finally { setPending(false); } }
  async function removeAccount() { if (!confirmDelete) return; setPending(true); setError(''); try { await accountsService.remove(confirmDelete.id); setUsers(current => current.filter(item => item.id !== confirmDelete.id)); setNotice('Cuenta eliminada.'); setConfirmDelete(null); } catch (err) { setError(err.message); setConfirmDelete(null); } finally { setPending(false); } }
  async function creditAccounts() { if (!creditIds.length) return setError('Selecciona al menos una cuenta para recargar.'); setPending(true); setError(''); try { const result = await accountsService.creditTokens(creditIds, Number(creditAmount), creditNote); setNotice(`${result.amount} tokens acreditados a ${result.credited.length} cuenta(s).`); setCreditIds([]); setCreditModal(false); } catch (err) { setError(err.message); } finally { setPending(false); } }
  return <section className="accounts-page">
    <div className="accounts-intro"><div><span className="eyebrow">CENTRO DE ADMINISTRACIÓN</span><h1>Tu comunidad, en orden<span>.</span></h1><p>{isSuperadmin ? 'Crea cuentas, asigna responsabilidades y controla los accesos desde un solo lugar.' : 'Consulta las cuentas y los roles de la comunidad.'}</p></div><div className="accounts-actions"><span className="accounts-label">◎ {labels[session.role]}</span>{isSuperadmin && <><button className="credit-accounts-button" onClick={() => { setError(''); setCreditModal(true); }}>◎ Recargar cuentas</button><button className="create-account-button" onClick={() => { setError(''); setCreating(true); }}>＋ Nueva cuenta</button></>}</div></div>
    <div className="account-stats">{[['Cuentas', users.length], ['Creadores', users.filter(item => item.role === 'creator').length], ['Equipo', users.filter(item => ['superadmin', 'admin', 'moderator'].includes(item.role)).length]].map(([label, count]) => <article key={label}><span>{label}</span><strong>{loading || error ? '—' : count}</strong></article>)}</div>
    {notice && <div className="admin-notice" role="status"><span>✓</span>{notice}<button aria-label="Cerrar aviso" onClick={() => setNotice('')}>×</button></div>}{error && !loading && <div className="admin-error" role="alert">{error}<button onClick={() => setError('')} aria-label="Cerrar error">×</button></div>}
    <section className="accounts-directory" aria-label="Directorio de cuentas"><div className="accounts-filters"><h2>Directorio</h2><input type="search" aria-label="Buscar cuentas" placeholder="Buscar por nombre o usuario" value={query} onChange={event => setQuery(event.target.value)} /><select aria-label="Filtrar por rol" value={role} onChange={event => setRole(event.target.value)}><option value="all">Todos los roles</option>{roles.map(item => <option key={item} value={item}>{labels[item]}</option>)}</select></div>
      {loading ? <p className="accounts-message" role="status">Cargando cuentas…</p> : error && !users.length ? <div className="accounts-message" role="alert"><p>{error}</p><button className="secondary-button" onClick={() => setRetry(retry + 1)}>Reintentar</button></div> : <><p className="accounts-count" role="status">{shown.length} {shown.length === 1 ? 'cuenta encontrada' : 'cuentas encontradas'}</p><div className="accounts-rows">{shown.map(account => <article key={account.id} className="account-row">{isSuperadmin && <input className="account-credit-check" type="checkbox" checked={creditIds.includes(account.id)} onChange={() => setCreditIds(current => current.includes(account.id) ? current.filter(id => id !== account.id) : [...current, account.id])} aria-label={`Seleccionar ${account.name || account.email} para recarga`}/>}<span className="account-avatar" aria-hidden="true">{(account.name || account.email)?.slice(0, 1)}</span><div className="account-identity"><strong>{account.name || 'Sin nombre'}{account.id === session.id && <small>Tú</small>}{account.protected_owner && <small>Propietario protegido</small>}</strong><span>{account.email}</span></div>{isSuperadmin ? <div className="account-controls"><select aria-label={`Rol de ${account.name || account.email}`} value={account.role} disabled={pending || account.id === session.id || account.protected_owner} onChange={event => changeRole(account, event.target.value)}>{roles.map(item => <option key={item} value={item}>{labels[item]}</option>)}</select><button className="remove-account" disabled={pending || account.id === session.id || account.protected_owner} onClick={() => setConfirmDelete(account)} aria-label={`Eliminar cuenta de ${account.name || account.email}`}>{account.protected_owner ? 'Protegida' : 'Eliminar'}</button></div> : <span className={'account-role role-' + account.role}>{labels[account.role]}</span>}</article>)}{!shown.length && <div className="accounts-message"><h3>Sin coincidencias</h3><p>Prueba con otro nombre o cambia el rol.</p><button className="secondary-button" onClick={() => { setQuery(''); setRole('all'); }}>Limpiar filtros</button></div>}</div></>}
    </section>
    <Modal open={creating} title="Crear una cuenta" onClose={() => !pending && setCreating(false)} className="account-modal"><p>Estas credenciales usarán el mismo inicio de sesión de Kinexy.</p><form onSubmit={createAccount}><label>Nombre<input required maxLength="100" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></label><label>Usuario o correo<input required maxLength="254" autoComplete="off" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>Contraseña temporal<input required minLength="8" maxLength="72" type="password" autoComplete="new-password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label><label>Rol<select value={form.role} onChange={event => setForm({ ...form, role: event.target.value })}>{roles.map(item => <option key={item} value={item}>{labels[item]}</option>)}</select></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={pending}>{pending ? 'Creando…' : 'Crear cuenta'}</button></form></Modal>
    <Modal open={creditModal} title="Recargar cuentas" onClose={() => !pending && setCreditModal(false)} className="credit-modal"><div className="credit-modal-intro"><span>RECARGA MASIVA DE PRUEBA</span><p>Selecciona cuentas del directorio y acredita tokens de forma inmediata.</p></div><div className="credit-modal-summary"><strong>{creditIds.length}</strong><span>cuentas seleccionadas</span><strong>{creditAmount || 0}</strong><span>tokens por cuenta</span></div><label>Tokens por cuenta<input type="number" min="1" max="10000" value={creditAmount} onChange={event => setCreditAmount(event.target.value)} /></label><label>Nota del movimiento<input value={creditNote} maxLength="140" onChange={event => setCreditNote(event.target.value)} placeholder="Ej. bono de bienvenida"/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={pending || !creditIds.length} onClick={creditAccounts}>{pending ? 'Acreditando…' : `Acreditar a ${creditIds.length} cuenta(s)`}</button><small className="credit-modal-help">Marca las cuentas con la casilla a la izquierda de cada fila.</small></Modal>
    <Modal open={Boolean(confirmDelete)} title="Eliminar cuenta" onClose={() => !pending && setConfirmDelete(null)} className="confirm-account-modal"><p>La cuenta de <strong>{confirmDelete?.name || confirmDelete?.email}</strong> perderá el acceso a Kinexy.</p><div><button className="secondary-button" disabled={pending} onClick={() => setConfirmDelete(null)}>Cancelar</button><button className="danger-button" disabled={pending} onClick={removeAccount}>{pending ? 'Eliminando…' : 'Eliminar cuenta'}</button></div></Modal>
  </section>;
}
