import AdminDashboard from './pages/AdminDashboard.jsx';
import MessagesPage from './pages/MessagesPage.jsx';
import MembershipsPage from './pages/MembershipsPage.jsx';
import DiscoverPage from './pages/DiscoverPage.jsx';
import AboutPage from './pages/AboutPage.jsx';
import React, { useEffect, useLayoutEffect, useState } from 'react';
import { Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import Header from './components/layout/Header.jsx';
import Footer from './components/layout/Footer.jsx';
import AgeGate from './components/layout/AgeGate.jsx';
import ProfileCard from './components/ui/ProfileCard.jsx';
import Modal from './components/ui/Modal.jsx';
import SearchBar from './components/ui/SearchBar.jsx';
import Toast from './components/ui/Toast.jsx';
import { PlansSection } from './components/ui/PlanCard.jsx';
import LoginPage from './pages/LoginPage.jsx';
import CreatorDashboard from './pages/CreatorDashboard.jsx';
import WalletPage from './pages/WalletPage.jsx';
import UserProfilePage from './pages/UserProfilePage.jsx';
import CreatorProfilePage from './pages/CreatorProfilePage.jsx';
import { profilesService } from './api/client';
import { useAuth } from './context/AuthContext';

const categories = ['Todos', 'Premium', 'A Domicilio', '18 años', 'Económicas', 'Maduras'];
function ScrollToTop() { const { pathname } = useLocation(); useLayoutEffect(() => { window.scrollTo(0, 0); }, [pathname]); return null; }
function Shell({ children, city = 'Pucallpa', setCity = () => {} }) { const navigate = useNavigate(); const { user, logout } = useAuth(); return <><Header onNavigate={navigate} city={city} onCityChange={setCity} user={user} onLogout={logout} />{children}<Footer onNavigate={navigate} /></>; }
function HomePage() { const [city, setCity] = useState('Pucallpa'); return <Shell city={city} setCity={setCity}><DiscoverPage city={city} setCity={setCity} /></Shell>; }
function CityPage() { const { city: slug } = useParams(); const cities = { pucallpa: 'Pucallpa', iquitos: 'Iquitos', tarapoto: 'Tarapoto', 'tingo-maria': 'Tingo María', yurimaguas: 'Yurimaguas' }; const city = cities[String(slug || '').toLowerCase()] || 'Todas'; const [selected, setSelected] = useState(city); return <Shell city={selected} setCity={setSelected}><DiscoverPage city={selected} setCity={setSelected} /></Shell>; }
function SectionPage({ title, text }) { const navigate = useNavigate(); return <Shell><main className="page section-page"><p className="eyebrow">Kinexy</p><h1>{title}</h1><p>{text}</p><button className="primary-button" onClick={() => navigate('/')}>Volver al inicio</button></main></Shell>; }
function AdminPage() { const { isModerator } = useAuth(); return isModerator ? <AdminDashboard /> : <Navigate to="/login" replace />; }
function AdvertiserPage() { const { isAdvertiser, isAdmin } = useAuth(); const [profiles, setProfiles] = useState([]); const [toast, setToast] = useState(''); const [form, setForm] = useState({ name: '', age: 18, city: 'Pucallpa', area: '', category: 'Premium', plan: 'basico', price: '', schedule: '', description: '', photo: 'photo-1' }); const load = () => profilesService.mine().then((r) => setProfiles(r.profiles)).catch(() => setProfiles([])); useEffect(() => { if (isAdvertiser || isAdmin) load(); }, [isAdvertiser, isAdmin]); if (!isAdvertiser && !isAdmin) return <Navigate to="/login" replace />; const submit = async (e) => { e.preventDefault(); try { await profilesService.create(form); setToast('Perfil enviado para revisión.'); setForm({ ...form, name: '', area: '', price: '', schedule: '', description: '' }); load(); } catch (err) { setToast(err.message); } }; const selectPlan = (plan) => { setForm((current) => ({ ...current, plan: plan.name.toLowerCase(), price: plan.price })); setToast(`Plan ${plan.name} seleccionado.`); }; return <Shell><main className="page section-page"><p className="eyebrow">Área de anunciante</p><h1>Mis perfiles</h1><p>Administra tus publicaciones y envíalas a revisión.</p><div className="advertiser-layout"><form className="profile-form" onSubmit={submit}>{[['name','Nombre'],['age','Edad'],['area','Zona'],['price','Precio'],['schedule','Horario']].map(([key,label]) => <label key={key}>{label}<input required={key === 'name' || key === 'age' || key === 'area'} type={key === 'age' ? 'number' : 'text'} value={form[key]} onChange={(e) => setForm({ ...form, [key]: key === 'age' ? Number(e.target.value) : e.target.value })} /></label>)}<label>Categoría<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.slice(1).map((x) => <option key={x}>{x}</option>)}</select></label><label>Descripción<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button className="primary-button">Crear perfil</button></form><section><h2>Publicaciones</h2>{profiles.map((p) => <article className="dashboard-row" key={p.id}><div><strong>{p.name}</strong><p>{p.city} · {p.category} · {p.approved ? 'Aprobado' : 'En revisión'}</p></div></article>)}{!profiles.length && <div className="empty-state">Todavía no tienes perfiles.</div>}</section></div><section className="plans-section"><h2>Elige un plan para tu publicación</h2><p>Selecciona una opción para completar el precio y la visibilidad del perfil.</p><PlansSection onSelect={selectPlan} /></section></main><Toast message={toast} type={toast.includes('error') ? 'error' : 'success'} onClose={() => setToast('')} /></Shell>; }
export default function App() { return <><AgeGate/><ScrollToTop/><Routes><Route path="/compra-demo" element={<Navigate to="/wallet" replace />} /><Route path="/" element={<HomePage />} /><Route path="/escorts/:city" element={<CityPage />} /><Route path="/creators/:id" element={<Shell><CreatorProfilePage /></Shell>} /><Route path="/about" element={<Shell><AboutPage /></Shell>} /><Route path="/memberships" element={<Shell><MembershipsPage /></Shell>} /><Route path="/messages" element={<Shell><MessagesPage /></Shell>} /><Route path="/profile" element={<Shell><UserProfilePage /></Shell>} /><Route path="/login" element={<LoginPage />} /><Route path="/register" element={<LoginPage />} /><Route path="/register/creator" element={<LoginPage />} /><Route path="/wallet" element={<Shell><WalletPage /></Shell>} /><Route path="/private" element={<SectionPage title="Kinexy Private" text="Acceso premium y experiencias privadas para usuarios registrados." />} /><Route path="/advertiser" element={<Shell><CreatorDashboard /></Shell>} /><Route path="/admin" element={<AdminPage />} /><Route path="/strategy" element={<SectionPage title="Modelo operativo" text="Información sobre planes y verificación." />} /><Route path="/legal" element={<SectionPage title="Términos y seguridad" text="La seguridad y privacidad son parte central de Kinexy." />} /><Route path="/privacy" element={<SectionPage title="Política de privacidad" text="Consulta cómo protegemos tus datos." />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></>; }
